dataset: 
  type: real
  name: humor
  path: ./datasets/affect/humor/humor.pkl
  num_classes: 2
  args: 
    batch_size: 64
    max_pad: True
    data_type: humor
    task: classification
    norm_modal: ["vision", "audio"]
  tokenize: False
model: 
  0:
    model_type: transformer
    n_features: 371
    hidden_dim: 371
    nhead: 1
    max_seq_length: 50
    use_cls_token: True
    tokenize: False
    norm_first: False
  1:
    model_type: transformer
    n_features: 81
    hidden_dim: 81
    nhead: 1
    max_seq_length: 50
    use_cls_token: True
    tokenize: False
    norm_first: False
  2:
    model_type: transformer
    n_features: 300
    hidden_dim: 300
    nhead: 1
    max_seq_length: 50
    use_cls_token: True
    tokenize: False
    norm_first: False
  setting: uni