dataset: 
  type: real
  name: mosi
  path: ./datasets/affect/mosi/mosi_data.pkl
  num_classes: 1
  args: 
    batch_size: 64
    max_pad: True
    data_type: mosi
    task: regression
    norm_modal: ["vision", "audio"]
  tokenize: False
model: 
  0:
    model_type: transformer
    n_features: 20
    hidden_dim: 20
    nhead: 1
    max_seq_length: 50
    use_cls_token: False
    tokenize: False
    norm_first: False
  1:
    model_type: transformer
    n_features: 5
    hidden_dim: 5
    nhead: 1
    max_seq_length: 50
    use_cls_token: False
    tokenize: False
    norm_first: False
  2:
    model_type: transformer
    n_features: 300
    hidden_dim: 300
    nhead: 1
    max_seq_length: 50
    use_cls_token: False
    tokenize: False
    norm_first: False
  setting: uni